# Generated by Django 6.1 on 2026-08-24 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecasting', '0001_initial'),
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField()),
                ('actual_generation_kwh', models.FloatField()),
                ('predicted_generation_kwh', models.FloatField()),
                ('deviation_kwh', models.FloatField()),
                ('performance_percentage', models.FloatField()),
                ('status', models.CharField(default='Normal', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='forecasting.forecastrecord')),
                ('solar_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='solar.solarsystem')),
            ],
        ),
    ]
