# Generated by Django 6.1 on 2026-08-24 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_GENERATION', 'Low Generation'), ('LOW_PERFORMANCE', 'Low Performance'), ('HIGH_DEVIATION', 'High Prediction Deviation'), ('SYSTEM_ISSUE', 'System Issue')], max_length=30)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solar_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='solar.solarsystem')),
            ],
        ),
    ]
