# Generated by Django 6.1 on 2026-09-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='created_at',
            new_name='alert_date',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='is_read',
            new_name='is_resolved',
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('Performance', 'Performance'), ('Generation', 'Generation'), ('Weather', 'Weather'), ('Maintenance', 'Maintenance')], max_length=30),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('Info', 'Info'), ('Warning', 'Warning'), ('Critical', 'Critical')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
