# Generated by Django 6.1 on 2026-08-22 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('cloud_cover', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('solar_irradiance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solar_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='solar.solarsystem')),
            ],
        ),
    ]
