# Generated by Django 6.1 on 2026-09-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarsystem',
            name='electricity_rate',
            field=models.FloatField(default=7.0),
        ),
    ]
