# Generated by Django 6.1 on 2026-09-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_solarsystem_electricity_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarsystem',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
