# Generated by Django 6.1 on 2026-08-22 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_generation_kwh', models.FloatField()),
                ('model_name', models.CharField(default='Random Forest', max_length=100)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solar_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_records', to='solar.solarsystem')),
            ],
        ),
    ]
